### ISSUE TITLE
SmartAlarm App crashing almost immediately after Go Live

### ISSUE THREAD

**Issue by Henri06522** [athombv/homey#1100]
**What is your Homey version (Settings → System)?**

v1.0.1

**What did you try to achieve?**

I've installed the Homey SmartAlarm App (v1.1.0) and in 15 minutes the application crashes.
I've connected the App succesfully by entering my SmartAlarm Credentials.

**What was the result?**

Crash with following log details

Stack trace:

TypeError: Cannot read property 'id' of undefined
at Object.trigger_state (/drivers/smartalarm/driver.js:229:29)
at emitThree (events.js:97:13)
at Object.emit (events.js:175:7)
at /homey-app/manager/flow.js:1:211
at /homey-app/helpers/client.js:1:1077
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:1046)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)
at internal/child_process.js:696:12

Exit code: 1
**What did you expect as result?**

...

**Any other remarks**

After a reboot app works again, but only for 15-60 minutes.

**Comment by BasKiers** [comment]
Hi,

I've fixed the issue. It should be working as of v1.1.1. Thank you for reporting the crash!

Regards,
Bas

**Comment by Mwahhh** [comment]
Tried to install the new app and add smartalarm, but after the credential check with smart alarm (and check the smartalarm that I want to add) I get a 'Invalid driver' pop-up. In the apps I see the following Stack trace:

TypeError: callback is not a function
at Request._callback (/drivers/smartalarm/driver.js:334:12)
at Request.self.callback (/node_modules/request/request.js:197:22)
at emitTwo (events.js:87:13)
at Request.emit (events.js:172:7)
at Request.<anonymous> (/node_modules/request/request.js:1050:14)
at emitOne (events.js:82:20)
at Request.emit (events.js:169:7)
at IncomingMessage.<anonymous> (/node_modules/request/request.js:996:12)
at emitNone (events.js:72:20)
at IncomingMessage.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:921:12)
at nextTickCallbackWith2Args (node.js:442:9)
at process._tickCallback (node.js:356:17)

Exit code: 1
Exit signal: null
