### ISSUE TITLE
Homey Doesnt contain node module node-homey-log so crashes app immediately

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1179]
**What is your Homey version (Settings → System)?**

1.0.5

**What did you try to achieve?**

that homey would contain  the node-homey-log module  like util and http 

there is nowhere documented which modules homey has onboard

with constant  Log = require('homey-log').Log;  in the app.js

**What was the result?**

app crashes because 

Stack trace:

Error: Cannot find module 'homey-log'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/app.js:8:11)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)

Exit code: 1
Exit signal: null

**What did you expect as result?**

that homey would contain the node module node-homey-log because EVERY app is expected to use this module 

**Any other remarks**

the adding of the module to the map node-modules is documented nowhere in the read.me of the repository, nor in the support pages of athom for developers

https://github.com/athombv/node-homey-log

...

**Comment by WeeJeWel** [comment]
Homey has no modules on board, so essentially every [non-nodejs native module](https://nodejs.org/api/) must be required.
