### ISSUE TITLE
Homey-Gotchi crash on 1.5 rc2

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1705]
**What is your Homey version (Settings → System)?**
1.5 rc2

**What did you try to achieve?**
run Homey-Gotchi

*Please include detailed steps how we can reproduce the issue*
Hi!

Unfortunately, the app crashed while I was doing the following:

Draaien op 1.5.x

_
This is the stack trace:

/lib/SoundManager.js:23
		callback = callback || () => {};
		                        ^

SyntaxError: Unexpected token )
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/lib/Homeygotchi.js:5:22)`
_

**Please attach a Homey System log (Settings -> System -> Send Log)**
log 88C9C7E918

**Comment by WeeJeWel** [comment]
Auch! I am very sorry. Unfortunately, HomeyGotchi is not supported anymore. ;)
