### ISSUE TITLE
windows install desktop app JAVA error

### ISSUE THREAD

**Issue by bramsel** [athombv/homey#1753]
Whenever I try to install the Homey Desktop App I get the following error prior to the setup installation:

ERROR

A JavaScript error occured in the main process

Uncaught Exception:
TypeError: callback is not a function
 at ChildProcess.spawned.on
(C:\users\quind\AppData\Local\athom\app-1.03\resources\app.asar\main\updater.js:169:3)
 at emitTwo events (events.js:106:13)
 at ChildProcess.emit (events.js:191:7)
at MaybeClose (internal/child_process.js:885:16)
at Process.ChildProcess_handle.onexit (internal/child_process.js:226:5)

After that it just quits the setup and nothing else happens.

**Comment by CyberSponk** [comment]
Windows? If Windows: 7, 8, 10?

**Comment by bramsel** [comment]
Windows 10, now now its a bug in HOMEY.

**Comment by CyberSponk** [comment]
Try to install it as Administrator > Right-Klick on Setup-File > Run as Administrator.
