### ISSUE TITLE
[ Docs SDK2 ]    advise not working 

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1918]
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**

use one capabilty more then once in a device, described in 
https://developer.athom.com/docs/apps/tutorial-Drivers-Capabilities.html

"Using the same capability more than once
In certain cases it might occur that a device should use a capability more than once. An example would be a device with an outside and inside temperature sensor. Simply append a dot followed by an identifier after the capability string during in your driver, e.g. measure_temperature.inside & measure_temperature.outside."

**What was the result?**
/drivers/nt20/device.js:110
    onCapabilityMeasure_temperature.one(value, opts, callback) {
tryout 1                                   ^

SyntaxError: Unexpected token .
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
    at require (internal/module.js:11:18)

tryout2

onCapability['Measure_temperature.one'](value, opts, callback) {
                ^

SyntaxError: Unexpected token [
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
    at require (internal/module.js:11:18)

tryout3 

2017-10-23 21:15:53 [log] [MyApp] MyApp is running...
/drivers/nt20/device.js:110
   onCapability('Measure_temperature.one')  (value, opts, callback) =>{
                ^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
    at require (internal/module.js:11:18)

...

**What did you expect as result?**

that the advised way the docs show would work

**Any other remarks**

a place to put these comments together would be nice

**Comment by jeroenvollenbrock** [comment]
All three provided code snippets do indeed contain invalid JavaScript. a dot ('.') is not an allowed character in an identifier. Please note that the name of your function is unrelated to the name of the capability, it is merely the name of the function that is registered (and thus referenced) using [registerCapabilityListener](https://developer.athom.com/docs/apps/Device.html#registerCapabilityListener).

**Comment by RobinBol** [comment]
Just a hint, I looked at your repo and see you use `measure_temperature_one` which should be `measure_temperature.one` and then also `this.registerCapabilityListener('measure_temperature.one', this.onCapabilityMeasure_temperature_one.bind(this))`.

**Comment by nattlip** [comment]
i got it.
