### ISSUE TITLE
URGENT:  Homeyscript not working anymore after automatic update to version 1.0.3

### ISSUE THREAD

**Issue by tboudri** [athombv/homey#2183]
Today Homeyscript was updated automatically. Now, scripts are not working anymore. Problem is that Promise.all is not working anymore. in the console i see the following in the error part of the Promise.all:

ReferenceError: headers is not defined
    at t.<anonymous> (/node_modules/athom-api/dist/index.js:1:875478)
    at n (/node_modules/athom-api/dist/index.js:1:197433)
    at Generator._invoke (/node_modules/athom-api/dist/index.js:1:198475)
    at Generator.e.(anonymous function) [as next] (/node_modules/athom-api/dist/index.js:1:197612)
    at a (/node_modules/athom-api/dist/index.js:1:5154)
    at /node_modules/athom-api/dist/index.js:1:5302
    at Promise (<anonymous>)
    at t (/node_modules/athom-api/dist/index.js:1:21167)
    at t.<anonymous> (/node_modules/athom-api/dist/index.js:1:5096)
    at t.e.value (/node_modules/athom-api/dist/index.js:1:875626)

Update: problem seems to be related to  getting BetterLogic variables with apiGet. And not only with Promise.all but also getting one variable

**Metadata**

* **Homey Version**: 1.5.3
* **Homey Log Code**: 89D949805E
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**: 1.0.3
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**Comment by jeroenvollenbrock** [comment]
Hi! Can you paste the code snippet that fails to execute please?

**Comment by tboudri** [comment]
`Homey.apps.getApp({ id: 'net.i-dev.betterlogic' } ).then( ( bl ) => {

    const proms =[
        bl.apiGet('werkkamer_licht_mode'),
        bl.apiGet('MODE'),
    ]
    Promise.all(proms).then( results => {
        log(results)
    }, e => {
        log(e);

    })

} )

`

**Comment by jeroenvollenbrock** [comment]
Fixed in 1.0.4
