### ISSUE TITLE
Apps SDK2  Docs does have an incorrect example of how to define a signal

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#2276]
**What did you try to achieve?**
make my first sdk2 app with a 433 signal

**what did you expect**
that the example code was working

**What was the result?**
node errors

following the guideline on
https://developer.athom.com/docs/apps/tutorial-Signals.html

2018-02-28 19:51:58 [log] [MyApp] MyApp is running...
/app.js:12
        let mySignal = new Signal433('x10');
                       ^

ReferenceError: Signal433 is not defined
    at MyApp.onInit (/app.js:12:24)
    at fs.stat.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js:1:3280)
    at FSReqWrap.oncomplete (fs.js:153:5)

it should be               let mySignal = new Homey.Signal( 'x10', '433');

**Comment by jeroenvollenbrock** [comment]
Fixed
