### ISSUE TITLE
Error: Cannot find module 'homey-rfdriver'

### ISSUE THREAD

**Issue by mstrunk101** [athombv/homey#2476]
Hallo,

The app does not want to start.

Stack trace:

module.js:540
throw err;
^

Error: Cannot find module 'homey-rfdriver'
at Function.Module._resolveFilename (module.js:538:15)
at Function.Module._load (module.js:468:25)
at Module.require (module.js:587:17)
at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
at require (internal/module.js:11:18)
at Object.<anonymous> (/drivers/ABST-604/driver.js:4:18)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)

Exit code: 1
Exit signal: null

**Comment by bvdbos** [comment]
please ask questions like this on Github or the forum and do a search first.... This is not a bug in Homey but a module you need to include...

**Comment by WeeJeWel** [comment]
Please create a new issue with more details.
