### ISSUE TITLE
[com.xiaomi-mi-zigbee] message: 'forced_timeout'

### ISSUE THREAD

**Issue by sprut666666** [athombv/homey#2533]
* **Homey Version**: 1.5.11
* **App**: https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/curtain/device.js

[err] [ManagerDrivers] [curtain] [0] Error: could not perform goToLiftPercentage on closuresWindowCovering { Error: forced_timeout
   at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1103)
   at JSON.parse (<anonymous>)
   at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1001)
   at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1401)
   at Array.map (<anonymous>)
   at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1386)
   at emitTwo (events.js:126:13)
   at process.emit (events.js:214:7)
   at emit (internal/child_process.js:772:12)
   at _combinedTickCallback (internal/process/next_tick.js:141:11)
   at process._tickCallback (internal/process/next_tick.js:180:9) message: ‘forced_timeout’ }

need help

**Comment by permadm** [comment]
+1
I have same problem

**Comment by Maxwell70** [comment]
+1
I have same problem

**Comment by tsvdonsk** [comment]
+1

**Comment by sprut666666** [comment]
The problem occurs specifically here, and it's very similar to the problem outside the plugin.
this.registerCapability('dim', 'closuresWindowCovering', {
				set: 'goToLiftPercentage',
				setParser(value) {
					return {
						percentageliftvalue: value * 100
					};
				},
				get: 'currentPositionLiftPercentage',
				report: 'currentPositionLiftPercentage',
				reportParser(value) {
					return value / 100;
				},
				endpoint: 0,
				getOpts: {
					getOnStart: true,
				},
			});
If it's a plug-in problem, can you help find the error?

**Comment by sprut666666** [comment]
@RobinBol If it's a plug-in problem, can you help find the error?
https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/75
