### ISSUE TITLE
com.ikea.tradfri.gateway app crashes on aut save on 1.5.13-rc.11 but works on 1.5.12

### ISSUE THREAD

**Issue by rogierhofboer** [athombv/homey#2891]
**Metadata**

* **Homey Version**: 1.5.13-rc.11
* **Homey Log Code**:  ?
* **Smartphone Platform**: N/A
* **Smartphone App Version**: N/A

**If related to a Homey App:** com.ikea.tradfri.gateway
* **Homey App Version**: 0.0.4 (alpha)
* **Homey App Log Code**: c6129e1f-0ba8-4182-8bf4-ccdc6d4c54b2
* **Affected Devices (preferably product codes)**: -

**What did you try to achieve?**
Save the authentication in the com.ikea.tradfri.gateway app

**What did you expect as result?**
Saved authentication

**What was the result?**
App crash

**Any other remarks**

Reason for reporting here is it seems to work at 1.5.12 but crashes at 1.5.13-rc.11
So maybe this could be a bug in the latest Homey RC

Hi! Unfortunately, the app crashed while I was doing the following: Saving auth (...) 

This is the stack trace: undefined:1 SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at parsePayload (/node_modules/node-tradfri-client/build/tradfri-client.js:757:25) at TradfriClient.handleNonSuccessfulResponse (/node_modules/node-tradfri-client/build/tradfri-client.js:578:25) at TradfriClient.observeScene_callback (/node_modules/node-tradfri-client/build/tradfri-client.js:553:23) at PendingRequest.handleResponse [as callback] (/node_modules/node-tradfri-client/build/tradfri-client.js:519:41) at Function.onMessage (/node_modules/node-coap-client/build/CoapClient.js:606:33) at emitTwo (events.js:126:13) at SocketWrapper.emit (events.js:214:7) at SocketWrapper.socket.on (/node_modules/node-coap-client/build/lib/SocketWrapper.js:12:18) at emitTwo (events.js:126:13)

Q&A to user:

_Did you see this only once or can you reproduce it consistently?_
I can do it constantly when I press save. If I restart program and have the data filled in it chrash immidiately. At our facebook group whe probably figured out why.
People who run Homey version 1.5.12 get it working. However I run 1.5.13-rc11 

*Crash log*

A crash occurred for your app (version 0.0.4) at Oct 24, 2018 4:28 PM (UTC).

Homey software version: 1.5.13-rc.11

Crash report:

    
Note: this log has been manually submitted by a user.
Log ID: c6129e1f-0ba8-4182-8bf4-ccdc6d4c54b2

---- stdout ----
2018-10-24 18:27:04 [log] [IkeaTradfriGatewayApp] Tradfri Gateway App has been initialized
2018-10-24 18:27:04 [log] [ManagerDrivers] [light] Tradfri Light Driver has been initialized
2018-10-24 18:27:04 [log] [ManagerDrivers] [group] Tradfri Group Driver has been initialized
2018-10-24 18:27:04 [log] [IkeaTradfriGatewayApp] Cannot read property 'startsWith' of null
2018-10-24 18:27:24 [log] [IkeaTradfriGatewayApp] vardagsrummet tak 1 updated
2018-10-24 18:27:24 [log] [IkeaTradfriGatewayApp] vardagsrummet tak 2 updated
2018-10-24 18:27:24 [log] [IkeaTradfriGatewayApp] TRADFRI bulb E27 W opal 1000lm 2 updated
2018-10-24 18:27:24 [log] [IkeaTradfriGatewayApp] Golvlampa updated
2018-10-24 18:27:24 [log] [IkeaTradfriGatewayApp] TRADFRI bulb GU10 W 400lm updated
2018-10-24 18:27:24 [log] [IkeaTradfriGatewayApp] TRADFRI bulb GU10 W 400lm 2 updated
2018-10-24 18:27:24 [log] [IkeaTradfriGatewayApp] TRADFRI bulb GU10 W 400lm 3 updated
2018-10-24 18:27:24 [log] [IkeaTradfriGatewayApp] TRADFRI bulb GU10 W 400lm 4 updated
2018-10-24 18:27:24 [log] [IkeaTradfriGatewayApp] Group Hallenj updated
2018-10-24 18:27:24 [log] [IkeaTradfriGatewayApp] Group Vardagsrum tak updated
2018-10-24 18:27:24 [log] [IkeaTradfriGatewayApp] Group entré updated
2018-10-24 18:27:24 [log] [IkeaTradfriGatewayApp] Group Vardagsrum updated
2018-10-24 18:27:25 [log] [IkeaTradfriGatewayApp] Group Kök updated

---- stderr ----
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parsePayload (/node_modules/node-tradfri-client/build/tradfri-client.js:757:25)
    at TradfriClient.handleNonSuccessfulResponse (/node_modules/node-tradfri-client/build/tradfri-client.js:578:25)
    at TradfriClient.observeScene_callback (/node_modules/node-tradfri-client/build/tradfri-client.js:553:23)
    at PendingRequest.handleResponse [as callback] (/node_modules/node-tradfri-client/build/tradfri-client.js:519:41)
    at Function.onMessage (/node_modules/node-coap-client/build/CoapClient.js:606:33)
    at emitTwo (events.js:126:13)
    at SocketWrapper.emit (events.js:214:7)
    at SocketWrapper.socket.on (/node_modules/node-coap-client/build/lib/SocketWrapper.js:12:18)
    at emitTwo (events.js:126:13)
  
N.B.: You will soon be able to view (an archive of) these logs from witin a developer panel on the app page.

**Comment by rogierhofboer** [comment]
No problem on 1.5.13 stable
