### ISSUE TITLE
Homey crash while running app in developers 

### ISSUE THREAD

**Issue by freemann** [athombv/homey#660]
**What is your Homey version (Settings → System)?**

0.8.35

**What did you try to achieve?**

Running a app in dev mode

**Please include detailed steps how we can reproduce the issue**

Running some code with mixed up callbacks 

**What was the result?**

A totally crashed Homey.

```
Error: Callback was already called.
    at /node_modules/async/dist/async.js:839:36
    at /drivers/tv/driver.js:77:17
    at process.<anonymous> (/homey-app/helpers/client.js:1:987)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:695:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
Disconnected from Homey, automatically reconnecting...
Trying to reconnect...
Trying to reconnect...
Trying to reconnect...
Trying to reconnect...
Trying to reconnect...
Trying to reconnect...
Trying to reconnect...
Trying to reconnect...
Trying to reconnect...

```
**What did you expect as result?**

a running app and/or save shutdown/kill of the app.

**Any other remarks**

**Comment by freemann** [comment]
Nope..... will close the issue.
