### ISSUE TITLE
[KAKU][0.8.39] Kaku App crashed on new FW .39.

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#694]
**What is your Homey version (Settings → System)?**
0.8.39 / KAKU 1.1.6
**What did you try to achieve?**
testing KAKU devices and flows after upgrade to .39

*Please include detailed steps how we can reproduce the issue*
tested sensor viewing device status in devices.

**What was the result?**
Contact sensor worked, just a couple of minutes later device unavailable: KAKU app crashed!

Stack trace:
TypeError: Cannot read property 'variables' of undefined
at Object.module.exports.self.capabilities.alarm_contact.get (/drivers/contactSensor/driver.js:127:28)
at /homey-app/manager/drivers.js:1:3049
at Object.drivers.(anonymous function).ready (/homey-app/manager/drivers.js:1:2053)
at eventListeners.clientDriver (/homey-app/manager/drivers.js:1:2420)
at /homey-app/helpers/client.js:1:868
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:835)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)
at handleMessage (internal/child_process.js:695:10)
at Pipe.channel.onread (internal/child_process.js:440:11)
...
Log: B25C46F5EF

**What did you expect as result?**
KAKU working.

**Any other remarks**

**Comment by Dennishacq** [comment]
@Dijker That's odd! Does this also happen when you re-add your device?

**Comment by Dijker** [comment]
I am mot sure if I already re-added them on .38, after the .39 I had some trouble like this msg. 
I haven't seen this anymore. 

After a Pull-the-Plug everything looks OK for now except the debouncer and ASUN 650 don't work correct anymore. :(  
Will create a new Issue for that
