### ISSUE TITLE
Woonveilig crash

### ISSUE THREAD

**Issue by bierre** [athombv/homey#720]
**What is your Homey version (Settings → System)?**

0.8.39

**What did you try to achieve?**

Use woonveilig app

**What was the result?**

There's an exclamation mark in the app window of homey next to woonveilig stating:

Stack trace:

TypeError: Cannot read property 'cookie' of undefined
at /drivers/woonveilig/driver.js:177:20
at Request._callback (/drivers/woonveilig/driver.js:130:20)
at self.callback (/node_modules/request/request.js:198:22)
at emitOne (events.js:77:13)
at Request.emit (events.js:169:7)
at Request.onRequestError (/node_modules/request/request.js:861:8)
at emitOne (events.js:77:13)
at ClientRequest.emit (events.js:169:7)
at TLSSocket.socketErrorListener (_http_client.js:256:9)
at emitOne (events.js:77:13)

**What did you expect as result?**

A working woonveilig app

**Any other remarks**

...

**Comment by BasKiers** [comment]
Should be fixed as of woonveilig v1.0.8
