### ISSUE TITLE
Forest app can be installed but cannot start.

### ISSUE THREAD

**Issue by cjvs** [athombv/homey#743]
**What is your Homey version (Settings → System)?**

Homey 0.9.1, Forest app 0.9.0

**What did you try to achieve?**

Install forest app on a clean and wiped homey and have it start

**What was the result?**

exclamation mark:
Stack trace:

Error: invalid_signal_id:[object Object]
at new Signal (/homey-app/various/rf.js:44:12)
at self.init (/drivers/shuttle.js:18:14)
at /homey-app/manager/drivers.js:1:2237
at Array.forEach (native)
at eventListeners.clientDriverInit (/homey-app/manager/drivers.js:1:757)
at /homey-app/helpers/client.js:1:868
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:835)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)

**What did you expect as result?**

installed and functional app

**Any other remarks**

none

**Comment by cjvs** [comment]
Updated to 0.9.2. Re-installed app. Issue remains

Stack trace:

Error: invalid_signal_id:[object Object]
at new Signal (/homey-app/various/rf.js:44:12)
at self.init (/drivers/shuttle.js:18:14)
at /homey-app/manager/drivers.js:1:2237
at Array.forEach (native)
at eventListeners.clientDriverInit (/homey-app/manager/drivers.js:1:757)
at /homey-app/helpers/client.js:1:868
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:835)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)

**Comment by cjvs** [comment]
Updated to 0.9.3 and installed version 0.11.1 of the forest app. Issue resolved.
