### ISSUE TITLE
[Osram Lightify] Turn on or off card doesn't triggers/Devices seem to time out

### ISSUE THREAD

**Issue by swttt** [athombv/homey#748]
**What is your Homey version (Settings → System)?**

0.9.1

**What did you try to achieve?**

Use the turn on or off card to turn the lights on or off. (No shit sherlock! 🐵 )

**What was the result?**

Works one time, then (i think) the device timed out. 

**What did you expect as result?**

To turn the lights on if they are off. And the other way around.

**Any other remarks**

I need to 'repair' them quite often since they time out again. (Trying to add them again seems to repair then, even if the wizard says no new devices found)

Just noticed that after repairing and turning them on or off. The state doesn't update, and the device will likely time out again.

**Comment by swttt** [comment]
Noticed that yesterday the api call returned "onoff = true" all the time. Tried to re-add the device, and for now that seems to work. Haven't seen a timeout yet. Still this must be a bug (had trouble with getting them added right in the beginning, had several errors)

**Comment by swttt** [comment]
Tried removing, and adding the devices again. Get invalid driver error. 
Can't seem to add the devices again. Will try to remove and re-install the lightify app.

`Stack trace:

TypeError: Cannot read property 'ip' of undefined
at EventEmitter.<anonymous> (/drivers/lightify_rgbw/driver.js:217:19)
at emitTwo (events.js:87:13)
at EventEmitter.emit (events.js:172:7)
at /homey-app/manager/drivers.js:1:4368
at Object.drivers.(anonymous function).ready (/homey-app/manager/drivers.js:1:2049)
at eventListeners.clientDriverPairMessage (/homey-app/manager/drivers.js:1:4258)
at /homey-app/helpers/client.js:1:868
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:835)
at emitTwo (events.js:87:13)`

Log: 4492B40A52

**Comment by bvdbos** [comment]
@swttt does this still happen?

**Comment by swttt** [comment]
Not using the lightify bridge anymore, cant tell.

**Comment by CyberSponk** [comment]
Got these and wait for Response from Support:

tack trace:

RangeError: index out of range
at checkOffset (buffer.js:696:11)
at Buffer.readUInt16LE (buffer.js:742:5)
at /node_modules/node-lightify/index.js:78:17
at responseProcesser (/node_modules/node-lightify/index.js:350:16)
at Lightify.<anonymous> (/node_modules/node-lightify/index.js:71:15)
at Socket.<anonymous> (/node_modules/node-lightify/index.js:42:50)
at emitOne (events.js:77:13)
at Socket.emit (events.js:169:7)
at readableAddChunk (_stream_readable.js:153:18)
at Socket.Readable.push (_stream_readable.js:111:10)
at TCP.onread (net.js:537:20)

Exit code: 1
Exit signal: null

**Comment by bvdbos** [comment]
does this still happen?

**Comment by RobinBol** [comment]
Will close this issue as the Homey App using the Lightify bridge has been deprecated, and the ZigBee version is released.
