### ISSUE TITLE
Testing of ledring animation through athom-cli results in error.

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey#947]
**What is your Homey version (Settings → System)?**
0.10.1

**What did you try to achieve?**
Develop a screensaver animation and use athom-cli for testing it as described here: https://developers.athom.com/library/ledring/#screensaver

**Please include detailed steps how we can reproduce the issue**
Just follow the steps in the documentation. Make a myanim.js that contains the screensaver animation and run the cli command to test it.

**What was the result?**
An error:
```
TypeError: Cannot read property '_id' of null
    at step2 (E:\Localhost\nodejs\node_modules\athom-cli\lib\ledring.js:29:62)
    at PromptUI.completed (E:\Localhost\nodejs\node_modules\athom-cli\lib\homey.js:44:4)
    at PromptUI.onCompletion (E:\Localhost\nodejs\node_modules\athom-cli\node_modules\inquirer\lib\ui\prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (E:\Localhost\nodejs\node_modules\athom-cli\node_modules\rx\dist\rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (E:\Localhost\nodejs\node_modules\athom-cli\node_modules\rx\dist\rx.js:1730:14)
    at AnonymousObserver.tryCatcher (E:\Localhost\nodejs\node_modules\athom-cli\node_modules\rx\dist\rx.js:567:29)
    at AutoDetachObserverPrototype.completed (E:\Localhost\nodejs\node_modules\athom-cli\node_modules\rx\dist\rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (E:\Localhost\nodejs\node_modules\athom-cli\node_modules\rx\dist\rx.js:1730:14)
    at InnerObserver.onCompleted (E:\Localhost\nodejs\node_modules\athom-cli\node_modules\rx\dist\rx.js:3425:65)
    at InnerObserver.tryCatcher (E:\Localhost\nodejs\node_modules\athom-cli\node_modules\rx\dist\rx.js:567:29)
```

**What did you expect as result?**
An ability tot test my screensaver animation through the command line without having to upload an app all the time.

**Any other remarks**
Nope

**Comment by DieterKoblenz** [comment]
Not receiving an error while following these steps but the ledring doesn't change.

**Comment by WeeJeWel** [comment]
Fixed in 0.10.2!

Sample animation:

```
'use strict';

var frames = [ [] ];
for( let i = 0; i < 24; i++ ) {

	let frame = {
		r: 0,
		g: 0,
		b: 0
	}

	if( i === 0 ) frame.r = 255;

	frames[0].push( frame );
}

let animation = {
    frames    	: frames,
    duration	: false,
    options: {
        fps     : 1,
        tfps    : 60,
        rpm     : 10
    }
}

module.exports = animation;
```

**Comment by jghaanstra** [comment]
I still recieve the same error on 0.10.3 but it could be my enviroment. Could you also have a check @DieterKoblenz so I can close the issue if it's resolved.

**Comment by DieterKoblenz** [comment]
Works here!

**Comment by jghaanstra** [comment]
Ok, I'll close this issue later today. Which nodejs version are you using?
Must be something in my environment that is causing this.

Op 6 okt. 2016 10:30 a.m. schreef "DieterKoblenz" <notifications@github.com

**Comment by DieterKoblenz** [comment]
PS F:\Homey\screensaver> node -v
v4.5.0

**Comment by jghaanstra** [comment]
Tried different NodeJS versions but keep getting the same error. It's obviously related to my own enviroment so I'm closing this issue.

**Comment by WeeJeWel** [comment]
Try logging in again, it seems your settings might be corrupted

**Comment by jghaanstra** [comment]
Refreshed my Homey and my athom-cli session but still with the same result (got a bit scared when Homey told me I dont have permission but trying it through my.athom.com worked).

But dont bother about my issue, it's not a big deal and there are bigger fish to try.

**Comment by aroramayank2002** [comment]
The example above as well as given on 
https://apps.developer.athom.com/tutorial-LED%20Ring.html

Didn't work for me. Frimware version 1.5.3.

Error on line:
// get access token
		homey = _.findWhere(global.settings.me.homeys, { _id: homey._id });

in ledring.js

**Comment by WeeJeWel** [comment]
I cannot reproduce the issue @aroramayank2002. Try logging out and back in again.
