### ISSUE TITLE
app settings and apps working very very strange

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#998]
**What is your Homey version (Settings → System)?**

0.10.5

**What did you try to achieve?**

to resuscitate my app which died with red three cornered exclamation sign in Homey settings page after update to 0.10.5

_Please include detailed steps how we can reproduce the issue_

five times :
1 removed and downloaded app from app-store . type in the settingspage of app, press save button 
result app crashes immediately.

2 did locally athom project --run .   app settings saved paired 35 devices runs 10 minutes .
ctrl -c in athon cli 

3 downloadend app again from app-store  , settings filled in works devices paired works . after 30 minutes the app disappears.....................................................

4 warm reboot try to get app back, but no app back and oregon scientific which is also reinstalled from app store after updating to 0.10.5 also disappeared.......................................

5 rerun plugwise from athom cli . all settings and devices are remembered from app store install but app crashes after 1 or 2 correct device readings from server......................................................................settings lost.....................................

6 rerun again from cli . the same result as in 5 , first 1 correct reading then app settings lost

7 after re- installing oregon app from appstore the oregon paired devices reappeard

8 after reainstalling plugwise from appstore waiting 10 minutes for pairing devices, it keeps running, added 1 device.

after 7 hours: 

9 next morning : all devices which were added in earlier steps reappeared minus 6 (29- 35).......

10 conclusion : installation hell .

**What was the result?**
see above

...

**What did you expect as result?**
no ghost apps no disappearing apps no reappearing apps , no reappearng devices.
...

**Any other remarks**

...

**Comment by bvdbos** [comment]
Strange thing is this only seems to happen with PW. Will try to confirm tonight...

**Comment by bvdbos** [comment]
Did some stripping down of the app. Put homey.ready() at the end of the function. Commented the error-handling. This both didn't work. When I commented the testing there were no errors anymore:
`        function onHomeyReady() {


            Homey.get('serverip', function (err, serverip) {
 //               if (err) return console.error('Could not get serverip', err);
                document.getElementById('ip').value = serverip;
            });
            Homey.get('serverport', function (err, serverport) {
 //               if (err) return console.error('Could not get serverport', err);
                document.getElementById('port').value = serverport;
            });

            Homey.get('serverpassword', function (err, serverpassword) {
 //               if (err) return console.error('Could not get password', err);
                document.getElementById('password').value = serverpassword;
            });

            Homey.get('serverusername', function (err, serverusername) {
 //               if (err) return console.error('Could not get username', err);
                document.getElementById('username').value = serverusername;
            });

 //           Homey.get('testing', function (err, testing) {
 //               //if (testing) { testing = false } else if (!testing) { testing = true };
 //               testingglobal = testing;
//
 //               if (err) return console.error('Could not get testing', err);
  //              document.getElementById("test").innerHTML = testing;
//            });


            // gets event data from app.js firesd in callback request
  //          Homey.on('my_event', function (data) {

//                if (data.plugwiseserverconnected)
//                    document.getElementById("connected").innerHTML = data.plugwiseserverconnected;
//                else if (data.testing)
//                document.getElementById("test").innerHTML = data.testing;
//            });
			
            Homey.ready()
        }`

So looks like an app-problem, not a Homey problem...

**Comment by nattlip** [comment]
an update for the plugwise app is pending for the appstore to solve this problem.

for now i know and think:

1  the problem didnt exist in earlier versions of the homey firmware
2  athom cli updated to new io node.js  version , i think homey also was updated with new io version
3 that api changes caused by homey api changes or io api changes cuased this new bug.

**Comment by nattlip** [comment]
second ptp before upgrading to 0.10.7 app store apps reappeared and the settings of plugwise disappeared. plugwise has to be geinstalled because of this , the app crashes in this state , zo no new settings can be typed in.

**Comment by bvdbos** [comment]
```app 25  plugiseserverset value : false
value ip setting input box 10.0.3.50
value port setting input box 8080
value user setting input box admin
value password  setting input box admin
value testing setting false
99 plugwiseserverconnected  false
plugwiseservertested  false
app 102 check if server is set     server is set
driver 103  before testserver if (self.plugwiseserverset)
 before req to be executed options2   { host: '10.0.3.50',
  port: '8080',
  path: '/statistics.xml',
  method: 'GET',
  auth: 'admin:admin' }
entered Homey.manager(settings).on(set, function (testing)
function (plugwiseservertested)the variable false
 156 testing  false
app 162 setting value of key serverip : 10.0.3.50
app 146 testing : 10.0.3.50
153 self.plugwiseservertested  false
app init 157init test
 before req to be executed options2   { host: '10.0.3.50',
  port: '8080',
  path: '/statistics.xml',
  method: 'GET',
  auth: 'admin:admin' }
driver 19 init driver
no device data
driver 174  callback2 entered
app 50         response on end
app 231    before   if (self.plugwiseservertested)       false
app 232   befor   if (response.statusCode == 200)       200
app 233   before    if (!self.plugwiseserverconnected)       true
app 237    after   if (self.plugwiseservertesting)       true
app 240   after    if (response.statusCode == 200)       200
app 268  after    if (!self.plugwiseserverconnected)       true
app 269  server isconnected
app 277   response.statusCode         200
app 277    self.testplugwiseserver     true
/api/  checkpath =  /stat
!(checkpath == /api/) true
driver 469  processdevcedata entered
enterd tranlateapplicance to appdevice
driver 377 onoff device data  { id: '000D6F0000AF4D4B' } true
driver 378 powerusage device data  { id: '000D6F0000AF4D4B' } 1
driver 379 meter power device data  { id: '000D6F0000AF4D4B' } 121
driver 377 onoff device data  { id: '000D6F0000D36BE2' } true
driver 378 powerusage device data  { id: '000D6F0000D36BE2' } 12
driver 379 meter power device data  { id: '000D6F0000D36BE2' } 116
driver 377 onoff device data  { id: '000D6F0000D341EF' } undefined
driver 378 powerusage device data  { id: '000D6F0000D341EF' } 0
driver 379 meter power device data  { id: '000D6F0000D341EF' } 53
 poller poller % stateModulus (poller % stateModulus) == 0) 2  0  true
driver 174  callback2 entered
app 50         response on end
app 231    before   if (self.plugwiseservertested)       true
app 232   befor   if (response.statusCode == 200)       200
app 233   before    if (!self.plugwiseserverconnected)       false
/api/  checkpath =  /stat
!(checkpath == /api/) true
driver 469  processdevcedata entered
enterd tranlateapplicance to appdevice
driver 377 onoff device data  { id: '000D6F0000AF4D4B' } true
driver 378 powerusage device data  { id: '000D6F0000AF4D4B' } 1
driver 379 meter power device data  { id: '000D6F0000AF4D4B' } 121
driver 377 onoff device data  { id: '000D6F0000D36BE2' } true
driver 378 powerusage device data  { id: '000D6F0000D36BE2' } 12
driver 379 meter power device data  { id: '000D6F0000D36BE2' } 116
driver 377 onoff device data  { id: '000D6F0000D341EF' } undefined
driver 378 powerusage device data  { id: '000D6F0000D341EF' } 0
driver 379 meter power device data  { id: '000D6F0000D341EF' } 53
 poller poller % stateModulus (poller % stateModulus) == 0) 2  0  true
```

with a stacktrace

```Stack trace:

TypeError: Cannot read property 'id' of undefined
at Object.self.capabilities.onoff.get (/drivers/circle/driver.js:142:78)
at /homey-app/manager/drivers.js:189:13
at Object.drivers.(anonymous function).ready (/homey-app/manager/drivers.js:131:9)
at eventListeners.clientDriverMessage (/homey-app/manager/drivers.js:170:10)
at /homey-app/manager/drivers.js:26:41
at Object.Homey.ready (/homey-app/homey.js:1:1008)
at /homey-app/manager/drivers.js:25:11
at /homey-app/helpers/client.js:1:1013
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:982)

Exit code: 1```

De-install and re-install works...

**Comment by nattlip** [comment]
@bvdbos , that is the same error as before, settings disappear at ptp, unfortunately i ha d 3 ptps because when i wrote 'all sockets on' in the speech input page or socket three on  homey set all sockets off including the circle of the homey.

**Comment by bvdbos** [comment]
As re-install works, I doubt this is a Hmey issue but maybe some leftover from last time when there was the undocumented API-change... Anyway, this should go in the PW-app until it's sure this is a Homey problem. Up till now this is the only app which shows this behaviour...

**Comment by nattlip** [comment]
@bvdbos  if i may summarize your last comment,  you dont know where the problem is , this is the only app with this behavior while i read a lot of lost settings and devices problems  in the z-wave department on slack. it is strange that in the procedure to update to 0.10.7 i do a ptp all apps disappear, then second ptp the app store installed apps reappear .  there is a saving probleem not only with my setting of plugwise. i dont know the answer either but jumping to conclusons is a bridge to far for me. if you dont know you dont know and have to accept that.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please let me know if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!
